language: java
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
before_install: "git clone -b travis `git config --get remote.origin.url` target/travis"
after_success: mvn deploy
branches:
  only:
  - master
notifications:
  email:
    recipients:
    - vatbub123+travisbuildnotification@googlemail.com
    on_success: never
    on_failure: always