language: java
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
before_install: "git clone -b travis `git config --get remote.origin.url` target/travis"
script: "[ ${TRAVIS_PULL_REQUEST} = 'false' ] && {[ ${TRAVIS_BRANCH} = release] && mvn clean deploy --settings target/travis/settings.xml || mvn test -B}
  || mvn clean verify --settings target/travis/settings.xml"
branches:
  only:
  - master
notifications:
  email:
    recipients:
    - vatbub123+travisbuildnotification@googlemail.com
    on_success: never
    on_failure: always