language: java
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
after_success: mvn deploy
notifications:
  email:
    recipients:
    - vatbub123+travisbuildnotification@googlemail.com
    on_success: never
    on_failure: always